### ISSUE TITLE
Access Denied When Trying To Upload Video

### ISSUE THREAD

**Issue by ahotrod** [MartNoten/transcribe-lambda-example#1]
CDK-deployed example into my AWS account with admin privileges.  Tried uploading .mp4 video via a http API web page, but get this error:

**<Code>AccessDenied</Code>

Any suggestions as to a fix?

May be a permissions issue with the created S3 mediabucket?

**Comment by MartNoten** [comment]
Hi @ahotrod,

Hope things have worked out.

In case you are still blocked, could you tell me what you mean with 'web page'? I'm assuming thats the S3 web console?

Looking at the error you send over it seems like your IAM user does not have the correct permissions to upload the file to the bucket. This should be seen in the IAM console. Depending on how your account is set up there could be a number of reasons for that to happen. 

Alternatively it could be that there is an extra Bucket policy added to the S3 bucket you are using. However, if you've deployed using the stack in this repository then that should not be the case.

Thanks.

**Comment by ahotrod** [comment]
Hello @MartNoten,

Thanks for your prompt response.  I added a http-api-lambda serverless CDK pattern to your excellent transcribe-lambda-example code.  After further inspection the problem is in my code.  Sorry to raise the issue in your github repository.

Best regards and thanks for sharing!
